--------------------------------------------------------
--  Fichier créé - jeudi-juillet-27-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EQUIPEMENT
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."EQUIPEMENT" 
   (	"ID" NUMBER(*,0), 
	"DATEA" NUMBER(*,0), 
	"NOME" VARCHAR2(20 BYTE), 
	"STATUT" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.EQUIPEMENT
SET DEFINE OFF;
Insert into SYSTEM.EQUIPEMENT (ID,DATEA,NOME,STATUT) values ('2','77','mm','ll');
Insert into SYSTEM.EQUIPEMENT (ID,DATEA,NOME,STATUT) values ('3','44','oo','yy');
Insert into SYSTEM.EQUIPEMENT (ID,DATEA,NOME,STATUT) values ('4','55','pp','hh');
Insert into SYSTEM.EQUIPEMENT (ID,DATEA,NOME,STATUT) values ('123','145','FF','DD');
--------------------------------------------------------
--  DDL for Index EQUIPEMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."EQUIPEMENT_PK" ON "SYSTEM"."EQUIPEMENT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table EQUIPEMENT
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."EQUIPEMENT" MODIFY ("DATEA" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."EQUIPEMENT" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."EQUIPEMENT" ADD CONSTRAINT "EQUIPEMENT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
