--------------------------------------------------------
--  Fichier créé - jeudi-juillet-27-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table HISTORY
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."HISTORY" 
   (	"ID" NUMBER, 
	"TYPE" VARCHAR2(20 BYTE), 
	"NUMIMMATRICULATION" NUMBER, 
	"DATE_HISTORIQUE" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.HISTORY
SET DEFINE OFF;
Insert into SYSTEM.HISTORY (ID,TYPE,NUMIMMATRICULATION,DATE_HISTORIQUE) values ('4444','ajout','88',to_date('01/05/23','DD/MM/RR'));
Insert into SYSTEM.HISTORY (ID,TYPE,NUMIMMATRICULATION,DATE_HISTORIQUE) values ('0','suppression','0',to_date('02/05/23','DD/MM/RR'));
Insert into SYSTEM.HISTORY (ID,TYPE,NUMIMMATRICULATION,DATE_HISTORIQUE) values ('1230','ajout','456',to_date('02/05/23','DD/MM/RR'));
Insert into SYSTEM.HISTORY (ID,TYPE,NUMIMMATRICULATION,DATE_HISTORIQUE) values ('300','ajout','1400',to_date('02/05/23','DD/MM/RR'));
Insert into SYSTEM.HISTORY (ID,TYPE,NUMIMMATRICULATION,DATE_HISTORIQUE) values ('100','suppression','300',to_date('02/05/23','DD/MM/RR'));
--------------------------------------------------------
--  DDL for Index HISTORY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."HISTORY_PK" ON "SYSTEM"."HISTORY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table HISTORY
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."HISTORY" ADD CONSTRAINT "HISTORY_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."HISTORY" MODIFY ("ID" NOT NULL ENABLE);
