--------------------------------------------------------
--  Fichier créé - jeudi-juillet-27-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PISTE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."PISTE" 
   (	"ID" NUMBER(*,0), 
	"NUMPISTE" NUMBER(*,0), 
	"LONGUEUR" NUMBER(*,0), 
	"LARGEUR" NUMBER(*,0), 
	"TYPE" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.PISTE
SET DEFINE OFF;
Insert into SYSTEM.PISTE (ID,NUMPISTE,LONGUEUR,LARGEUR,TYPE) values ('1','10','22','55','testt');
Insert into SYSTEM.PISTE (ID,NUMPISTE,LONGUEUR,LARGEUR,TYPE) values ('2','7','15','12','premier');
Insert into SYSTEM.PISTE (ID,NUMPISTE,LONGUEUR,LARGEUR,TYPE) values ('3','4','10','13','deuxieme');
Insert into SYSTEM.PISTE (ID,NUMPISTE,LONGUEUR,LARGEUR,TYPE) values ('8','52','88','99','oo');
Insert into SYSTEM.PISTE (ID,NUMPISTE,LONGUEUR,LARGEUR,TYPE) values ('0','0','0','0',null);
Insert into SYSTEM.PISTE (ID,NUMPISTE,LONGUEUR,LARGEUR,TYPE) values ('4','8','66','77','cent');
Insert into SYSTEM.PISTE (ID,NUMPISTE,LONGUEUR,LARGEUR,TYPE) values ('7','8','7','8','0');
--------------------------------------------------------
--  DDL for Index PISTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PISTE_PK" ON "SYSTEM"."PISTE" ("ID", "NUMPISTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table PISTE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PISTE" ADD CONSTRAINT "PISTE_PK" PRIMARY KEY ("ID", "NUMPISTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."PISTE" MODIFY ("NUMPISTE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PISTE" MODIFY ("ID" NOT NULL ENABLE);
