--------------------------------------------------------
--  Fichier créé - jeudi-juillet-27-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table RESERVATION
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."RESERVATION" 
   (	"ID" NUMBER(*,0), 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"TYPE_IMMATRICULATION" VARCHAR2(20 BYTE), 
	"NUMIMMATRICULATION" NUMBER(*,0), 
	"DATE_RES" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.RESERVATION
SET DEFINE OFF;
Insert into SYSTEM.RESERVATION (ID,NOM,PRENOM,TYPE_IMMATRICULATION,NUMIMMATRICULATION,DATE_RES) values ('1','chaieb','yousra','tn','206',to_date('05/05/23','DD/MM/RR'));
Insert into SYSTEM.RESERVATION (ID,NOM,PRENOM,TYPE_IMMATRICULATION,NUMIMMATRICULATION,DATE_RES) values ('2','omar','mahmoud','tn','199',to_date('05/05/23','DD/MM/RR'));
Insert into SYSTEM.RESERVATION (ID,NOM,PRENOM,TYPE_IMMATRICULATION,NUMIMMATRICULATION,DATE_RES) values ('3','dridi','yosser','tn','145',to_date('05/05/23','DD/MM/RR'));
--------------------------------------------------------
--  DDL for Index RESERVATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."RESERVATION_PK" ON "SYSTEM"."RESERVATION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table RESERVATION
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."RESERVATION" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."RESERVATION" ADD CONSTRAINT "RESERVATION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
