--------------------------------------------------------
--  Fichier créé - jeudi-juillet-27-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table VEHICULE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."VEHICULE" 
   (	"ID" NUMBER(*,0), 
	"KILOMETRAGE" NUMBER(*,0), 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"MARQUE" VARCHAR2(20 BYTE), 
	"MODELE" VARCHAR2(20 BYTE), 
	"NUMSERIE" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.VEHICULE
SET DEFINE OFF;
Insert into SYSTEM.VEHICULE (ID,KILOMETRAGE,NOM,PRENOM,MARQUE,MODELE,NUMSERIE) values ('2','55','yy','uuyy','yy','tt','5');
Insert into SYSTEM.VEHICULE (ID,KILOMETRAGE,NOM,PRENOM,MARQUE,MODELE,NUMSERIE) values ('7','77','oooo','oooo','uuu','uuu','88');
Insert into SYSTEM.VEHICULE (ID,KILOMETRAGE,NOM,PRENOM,MARQUE,MODELE,NUMSERIE) values ('3','55','yy','uuyy','yy','tt','5');
Insert into SYSTEM.VEHICULE (ID,KILOMETRAGE,NOM,PRENOM,MARQUE,MODELE,NUMSERIE) values ('4','55','yy','uuyy','yy','tt','5');
Insert into SYSTEM.VEHICULE (ID,KILOMETRAGE,NOM,PRENOM,MARQUE,MODELE,NUMSERIE) values ('123123','2121','POLLL','IUJ','BM','PMP','213');
Insert into SYSTEM.VEHICULE (ID,KILOMETRAGE,NOM,PRENOM,MARQUE,MODELE,NUMSERIE) values ('6','55','yy','uuyy','yy','tt','5');
Insert into SYSTEM.VEHICULE (ID,KILOMETRAGE,NOM,PRENOM,MARQUE,MODELE,NUMSERIE) values ('13150157146190','9871','MAYALI','SALEM','PEUG','TT','2399');
--------------------------------------------------------
--  DDL for Index VEHICULE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."VEHICULE_PK" ON "SYSTEM"."VEHICULE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table VEHICULE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."VEHICULE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."VEHICULE" MODIFY ("KILOMETRAGE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."VEHICULE" ADD CONSTRAINT "VEHICULE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
