--------------------------------------------------------
--  Fichier cr�� - jeudi-juillet-27-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table VISITE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."VISITE" 
   (	"ID" NUMBER(*,0), 
	"DATEVISITE" NUMBER(*,0), 
	"KILOMETRAGE" NUMBER(*,0), 
	"PRIXVISITE" NUMBER(*,0), 
	"RESULTAT" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.VISITE
SET DEFINE OFF;
Insert into SYSTEM.VISITE (ID,DATEVISITE,KILOMETRAGE,PRIXVISITE,RESULTAT) values ('1','20','122','144','Accepter');
Insert into SYSTEM.VISITE (ID,DATEVISITE,KILOMETRAGE,PRIXVISITE,RESULTAT) values ('8','10','10','10','Payée');
Insert into SYSTEM.VISITE (ID,DATEVISITE,KILOMETRAGE,PRIXVISITE,RESULTAT) values ('2','11','11','11','Payée');
Insert into SYSTEM.VISITE (ID,DATEVISITE,KILOMETRAGE,PRIXVISITE,RESULTAT) values ('0','54','222','222','Payée');
Insert into SYSTEM.VISITE (ID,DATEVISITE,KILOMETRAGE,PRIXVISITE,RESULTAT) values ('4','5','66','52','Non payée');
Insert into SYSTEM.VISITE (ID,DATEVISITE,KILOMETRAGE,PRIXVISITE,RESULTAT) values ('5','35333','555','558','Payée');
--------------------------------------------------------
--  DDL for Index VISITES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."VISITES_PK" ON "SYSTEM"."VISITE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index VISITES_FK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."VISITES_FK1" ON "SYSTEM"."VISITE" ("ID", "KILOMETRAGE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table VISITE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."VISITE" ADD CONSTRAINT "VISITES_PK" PRIMARY KEY ("ID", "KILOMETRAGE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."VISITE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."VISITE" MODIFY ("KILOMETRAGE" NOT NULL ENABLE);
